# Generated by Django 6.0.3 on 2026-04-09 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pwb", "0002_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("A1 Begginer", "A1 Begginer"),
                            ("A2 Elementary", "A2 Elementary"),
                            ("B1 Intermediate", "B1 Intermediate"),
                            ("B2 Upper-Intermediate", "B2 Upper-Intermediate"),
                            ("C1 Advanced", "C1 Advanced"),
                            ("C2 Advanced Proficy", "C2 Advanced Proficy"),
                            ("Native or Bilingual", "Native or Bilingual"),
                        ]
                    ),
                ),
                (
                    "pwb_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to="pwb.pwbunit",
                    ),
                ),
            ],
        ),
    ]
