# Generated by Django 6.0.3 on 2026-04-09 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pwb", "0003_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExperienceUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("from_date", models.DateField()),
                ("to_date", models.DateField()),
                (
                    "pwb_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experience_units",
                        to="pwb.pwbunit",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("to_date__gt", models.F("from_date"))),
                        name="experience_to_date_after_from_date",
                    )
                ],
            },
        ),
    ]
